import HeadBar from "@/components/header-bar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { env } from "process";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SiR Inhouse League",
  description: "Generated by create next app",
  verification: {
    google: env.GOOGLE_VERIFICATION,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeadBar />
        {children}
      </body>
    </html>
  );
}
